### ISSUE TITLE
POS tagging + compound splitting ?

### ISSUE THREAD

**Issue by noe** [rsennrich/clevertagger#2]
Would it be possible to do POS tagging on compound-splitted text processed with your script [`hybrid_compound_splitter.py`](https://github.com/rsennrich/wmt2014-scripts/blob/master/hybrid_compound_splitter.py) ?

P.S.: thanks a lot for all the great open source projects you share!

**Comment by rsennrich** [comment]
The appropriate thing to do is to produce two files:

1. the POS-tagged file based on the text before compound splitting
2. the compound-split text file

It is then straightforward to merge the two, with your own strategy what POS tags you want to assign for parts of the compound.

I did a similar merging here https://github.com/rsennrich/wmt16-scripts/blob/master/preprocess/conll_to_factors.py and here

**Comment by noe** [comment]
I was referring specifically to assigning POS tags to the parts of the compound.I understand that compounds can be formed with two nouns, but also with verb and noun, e.g. Esszimmer (to dine + room), Schreibmaschine (to write + machine), or with adjective and noun, e.g. Gebrauchtwagen (user + car).

My hope was to obtain POS tags of the invidiual parts of the compound by somehow combining those two tools. From your answer I understand this is not possible.

**Comment by rsennrich** [comment]
you can get a derivational analysis of compounds using SMOR (or Zmorge, which combines a Wiktionary lexicon with the SMOR grammar). Here's an example analysis.

```
original SMOR:
Vermittlungsgespräche
vermitteln<V>ung<NN><SUFF>Gespräch<+NN><Neut><Nom><Pl> 
```

you can download models, and see more instructions, here:
https://pub.cl.uzh.ch/users/sennrich/zmorge/
